version: "3"
services:
  db:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    driver: local
